// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhY9i-LeqRmTDU104myFwdqKI_VtA4uw8',
    appId: '1:350012490066:web:aa10d6bab36d609a363a8b',
    messagingSenderId: '350012490066',
    projectId: 'rngapp-69188',
    authDomain: 'rngapp-69188.firebaseapp.com',
    storageBucket: 'rngapp-69188.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiYsf-9kHBvNqGBRHCs7yS8OHrBJXuw34',
    appId: '1:350012490066:android:ede3c8cfbc140f1d363a8b',
    messagingSenderId: '350012490066',
    projectId: 'rngapp-69188',
    storageBucket: 'rngapp-69188.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOTj41ZqQZeRaI--_w_4AwMdBV8MCIWFA',
    appId: '1:350012490066:ios:775a92779e9c5e8c363a8b',
    messagingSenderId: '350012490066',
    projectId: 'rngapp-69188',
    storageBucket: 'rngapp-69188.firebasestorage.app',
    iosBundleId: 'com.example.rng',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOTj41ZqQZeRaI--_w_4AwMdBV8MCIWFA',
    appId: '1:350012490066:ios:775a92779e9c5e8c363a8b',
    messagingSenderId: '350012490066',
    projectId: 'rngapp-69188',
    storageBucket: 'rngapp-69188.firebasestorage.app',
    iosBundleId: 'com.example.rng',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhY9i-LeqRmTDU104myFwdqKI_VtA4uw8',
    appId: '1:350012490066:web:7c297a43ab7dcf86363a8b',
    messagingSenderId: '350012490066',
    projectId: 'rngapp-69188',
    authDomain: 'rngapp-69188.firebaseapp.com',
    storageBucket: 'rngapp-69188.firebasestorage.app',
  );
}
